export const MOST_SEARCHED_NICHES: string[] = [
  "Industrial Cleaning",
  "Plumbing",
  "Roofing",
  "Landscaping",
  "HVAC",
  "Pest Control",
  "Electrician",
  "Locksmith",
  "Painting",
  "Moving",
  "Auto Repair",
  "Lawn Care",
  "Window Cleaning",
  "Pool Service",
  "Tutoring",
  "Daycare",
  "Catering",
  "IT Support",
  "Home Security",
  "Photography",
];
